const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const styles = fs.readFileSync(path.join(__dirname, "..", "styles.css"), "utf8");
const main = fs.readFileSync(path.join(__dirname, "..", "main.js"), "utf8");
const primaryRule = styles.match(/\.paperlib-editor-actions > button\.mod-cta,[\s\S]*?\n\}/)?.[0] || "";
const secondaryRule = styles.match(/\.paperlib-editor-actions button:not\(\.mod-cta\),[\s\S]*?\n\}/)?.[0] || "";

assert.match(primaryRule, /\.paperlib-modal-buttons > button\.mod-cta/);
assert.match(primaryRule, /background:[\s\S]*linear-gradient[\s\S]*!important/);
assert.match(primaryRule, /color: #fff !important/);
assert.match(secondaryRule, /background: transparent/);
assert.doesNotMatch(styles, /\.paperlib-appearance-base-standard \.paperlib-icon-button\s*\{/);
assert.match(main, /DEFAULT_STANDARD_LIBRARY_COLUMNS = \["type", "title", "authors", "venue", "year", "notes"\]/);
assert.match(main, /standardTableColumns: \[\.\.\.DEFAULT_STANDARD_LIBRARY_COLUMNS\]/);
assert.match(main, /standardTableColumnWidths: \{\}/);
assert.match(main, /showStandardColumnMenu\(event\)/);
assert.match(main, /normalizeStandardTableColumns\(columns\)/);
assert.match(main, /normalizeStandardTableColumnWidths\(widths = \{\}\)/);
assert.match(main, /installStandardColumnResizer\(cell, key, label, table, columnOrder\)/);
assert.match(main, /installStandardColumnReorder\(cell, key\)/);
assert.match(main, /saveStandardTableColumnOrder\(order\)/);
assert.match(main, /重置全部列宽/);
assert.match(main, /"institution", "venue", "year", "rating"/);
assert.doesNotMatch(main, /standardCompact/);
assert.match(main, /paperlib-detail-toggle/);
assert.match(main, /paperlib-composer-toggle/);
assert.match(main, /showStandardLibraryActionsMenu\(event\)/);
assert.match(main, /paperlib-standard-utility-menu/);
assert.doesNotMatch(main, /paperlib-standard-attachment/);
assert.match(main, /data-paperlib-table-variant", "catalog"/);
assert.match(styles, /\.paperlib-appearance-standard\[data-paperlib-surface="library"\][\s\S]*data-paperlib-table-variant="catalog"/);
assert.match(styles, /\.paperlib-table-header \.paperlib-cell:last-child/);
assert.match(styles, /\.paperlib-paper-row \.paperlib-year/);
assert.match(styles, /order: 0;[\s\S]*cursor: grab/);
assert.doesNotMatch(styles, /paperlib-standard-density|is-standard-compact/);
assert.doesNotMatch(styles, /\.paperlib-appearance-standard\[data-paperlib-surface="library"\][^{]*\.paperlib-(?:sidebar|detail)/);
assert.match(main, /doubleClickOpenMode: "workspace"/);
assert.match(main, /\.setName\("双击论文条目时"\)/);
assert.match(main, /\.addOption\("workspace", "研究画布"\)/);
assert.match(main, /\.addOption\("pdf", "Obsidian PDF 阅读器"\)/);
assert.match(main, /\.addOption\("note", "论文笔记"\)/);
assert.match(main, /openPaperFromDoubleClick\(paper\)/);
assert.match(main, /if \(mode === "note"\) return this\.openOrCreateNote\(paper\)/);
assert.match(main, /if \(mode === "pdf"\) return this\.openPaperPdf\(paper, \{ native: true \}\)/);
assert.equal((main.match(/this\.plugin\.openPaperFromDoubleClick\(paper\)/g) || []).length, 3);
assert.match(styles, /\.modal\.paperlib-figure-gallery-modal \.paperlib-figure-thumbnail-card \{[\s\S]*?height: auto;[\s\S]*?min-height: 146px;[\s\S]*?white-space: normal;/);
assert.match(styles, /\.modal\.paperlib-figure-gallery-modal \.paperlib-figure-thumbnail-preview canvas \{[\s\S]*?position: absolute;[\s\S]*?width: 100%;[\s\S]*?height: 100%;[\s\S]*?object-fit: contain;/);

console.log("Paper Library primary button style tests passed.");
